<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<RootNamespace>$(MSBuildProjectName)</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>

	<ItemGroup>
	  <EmbeddedResource Include="内嵌资源\出生点.clip" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="TShock" Version="6.1.0" />
	</ItemGroup>
	

</Project>
